### ISSUE TITLE
Aulas sobre Resolução de Sistemas Lineares e Integração Numérica

### ISSUE THREAD

**Issue by vitorbertulucci** [fabiommendes/numericos-pub#11]
Professores, as aulas sobre os temas de Integração Numérica e Sistemas Lineares já estão para serem colocadas aqui no Git? Gostaria de pegá-los para já começar a ler para estudar para a prova final.

**Comment by fabiommendes** [comment]
Oi Vitor,

eu atualizei o git hoje de manhã e tem o notebook sobre sistemas lineares e
algumas melhorias na parte de EDO e quadraturas.

Abraço,
Fábio

2017-06-02 9:04 GMT-03:00 Vitor Bertulucci Borges <notifications@github.com>
:

**Comment by vitorbertulucci** [comment]
Valeu professor!

Abraço!
